// <auto-generated />
using System;
using ASP_DOTNET_CORE_WEB_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_DOTNET_CORE_WEB_API.Migrations
{
    [DbContext(typeof(PlayerDBContext))]
    partial class PlayerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP_DOTNET_CORE_WEB_API.Models.Domain.AccountData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonalDataID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerDataIDs")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerDatasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalDataID");

                    b.HasIndex("PlayerDatasId");

                    b.ToTable("accountDatas");
                });

            modelBuilder.Entity("ASP_DOTNET_CORE_WEB_API.Models.Domain.PersonalData", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("personalDatas");
                });

            modelBuilder.Entity("ASP_DOTNET_CORE_WEB_API.Models.Domain.PlayerData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Exp")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("playerDatas");
                });

            modelBuilder.Entity("ASP_DOTNET_CORE_WEB_API.Models.Domain.AccountData", b =>
                {
                    b.HasOne("ASP_DOTNET_CORE_WEB_API.Models.Domain.PersonalData", "PersonalData")
                        .WithMany()
                        .HasForeignKey("PersonalDataID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP_DOTNET_CORE_WEB_API.Models.Domain.PlayerData", "PlayerDatas")
                        .WithMany()
                        .HasForeignKey("PlayerDatasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalData");

                    b.Navigation("PlayerDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
